name: Keepalive Demo

on:
  push:
    branches: [ beta ]

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - run: |
        # Heroku 保活
        wget -q https://docker-yapi.herokuapp.com/ || true
